# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000
# test:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000

# production:
#   adapter: postgresql
#   database: db/production.psql
#   pool: 5
#   timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: db/development.psql
  pool: 5
  username: fightimpunityhaiti
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: db/test.psql
  pool: 5
  username: fightimpunityhaiti
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: db/production.psql
  pool: 5
  username: fightimpunityhaiti
  password: